### ISSUE TITLE
Bug: ciSCSIInitiator does not work when InitiatorPortalAddress is null

### ISSUE THREAD

**Issue by Zuldan** [PlagueHO/ciSCSI#6]
In our environment the InitiatorPortalAddress is null across all our servers. However, Get-TargetPortal requires you to provide a value for InitiatorPortalAddress. When Get-iSCSITargetPortal is run with InitiatorPortalAddress as null the CIM fails (of course). 

So -InitiatorPortalAddress should not be Mandatory.

PS C:\>> Get-iSCSITargetPortal

InitiatorInstanceName  : 
InitiatorPortalAddress : 
IsDataDigest           : False
IsHeaderDigest         : False
TargetPortalAddress    : MyTargetPortalHostname
TargetPortalPortNumber : 3260
PSComputerName         :

**Comment by PlagueHO** [comment]
Hi @Zuldan - I've fixed this issues #5 and #6 (hopefully). I've had a bit of trouble effectively testing them because all my iSCSI systems have separate networks assigned to iSCSI and so I have to use the InitiatorPortalAddress to force use of these iSCSI networks (and using the Hostname is out too).

I've made these changes to the Dev branch - but haven't pushed it to Master (or PSGallery yet). Are you able to give this version a try and see if it resolves your issues?

Thanks!

**Comment by Zuldan** [comment]
Really didn't expect you to work on this on the weekend, so thank you. Thanks to your changes, Test-Target is now working.

PS C:\> $iSCSIParams = @{
    Ensure                 = 'Present'
    TargetPortalAddress    = 'labiscsitarget01'
    TargetPortalPortNumber = 3260
    NodeAddress            = 'iqn.2003-10.com.riverbed:labiscsitarget01.000'
    #IsPersistent           = $True
}

import-module 'C:\Program Files\WindowsPowerShell\Modules\ciSCSI\1.1.0\DSCResources\BMD_ciSCSIInitiator\BMD_ciSCSIInitiator.psm1' -Force
BMD_ciSCSIInitiator\Test-TargetResource @iSCSIParams -Verbose
VERBOSE: Test-TargetResource: Testing iSCSI Initiator 'iqn.2003-10.com.riverbed:labiscsitarget01.000', 'labserver01' from ''.
VERBOSE: labiscsitarget01
True

However, Set-Target is throwing an error

VERBOSE: Set-TargetResource: Setting iSCSI Initiator 'iqn.2003-10.com.riverbed:labiscsitarget01.000', 'labserver01' from ''.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target Portal 'labiscsitarget01' from '' exists.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' is connected.
VERBOSE: labiscsitarget01
Disconnect-IscsiTarget : The session cannot be logged out since a device on that session is currently being used. 
At C:\Program Files\WindowsPowerShell\Modules\ciSCSI\DSCResources\BMD_ciSCSIInitiator\BMD_ciSCSIInitiator.psm1:448 char:21
+                     Disconnect-IscsiTarget `
+                     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_iSCSITarge...nztau01rfe0...):ROOT/Microsoft/...SFT_iSCSITarget) [Disconnect-IscsiTarget], CimException
    + FullyQualifiedErrorId : HRESULT 0xefff0040,Disconnect-IscsiTarget

My current settings below;

PS C:\> Get-IscsiSession


AuthenticationType      : NONE
InitiatorInstanceName   : ROOT\ISCSIPRT\0000_0
InitiatorNodeAddress    : iqn.1991-05.com.microsoft:labserver01.lab.local
InitiatorPortalAddress  : 0.0.0.0
InitiatorSideIdentifier : 400001370001
IsConnected             : True
IsDataDigest            : False
IsDiscovered            : False
IsHeaderDigest          : False
IsPersistent            : False
NumberOfConnections     : 1
SessionIdentifier       : ffffe000fe0e2020-4000013700000001
TargetNodeAddress       : iqn.2003-10.com.riverbed:labiscsitarget01.000
TargetSideIdentifier    : 2b00
PSComputerName          :

PS C:\> Get-IscsiConnection

ConnectionIdentifier : ffffe000fe0e2020-0
InitiatorAddress     : 0.0.0.0
InitiatorPortNumber  : 1472
TargetAddress        : 192.168.0.5
TargetPortNumber     : 3260
PSComputerName       :

PS C:\> Get-IscsiTarget

IsConnected NodeAddress                                  PSComputerName
----------- -----------                                  --------------
       True iqn.2003-10.com.riverbed:labiscsitarget01.000

PS C:\> Get-IscsiTargetPortal

InitiatorInstanceName  :
InitiatorPortalAddress :
IsDataDigest           : False
IsHeaderDigest         : False
TargetPortalAddress    : labiscsitarget01
TargetPortalPortNumber : 3260
PSComputerName         :

**Comment by Zuldan** [comment]
Ok I managed to get Set-Target to work.

PS C:\> BMD_ciSCSIInitiator\Set-TargetResource @iSCSIParams -Verbose
VERBOSE: Set-TargetResource: Setting iSCSI Initiator 'iqn.2003-10.com.riverbed:sxxnztau01rfe01.000', 'SXXNZTAU01RFE01' from ''.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target Portal 'labiscsitarget01' from '' exists.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' is connected.
VERBOSE: Set-TargetResource: iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' has been connected.

Just got a bit worried when I saw the Verbose doing changing 'blah blah' from ''.

Let me do some further testing...

**Comment by PlagueHO** [comment]
@Zuldan - not a problem :smile: I do enjoy this stuff.

Anyway, thanks for testing that - I think I know what might be going on here: the resource is incorrectly determining the session is connected to the wrong host because the TargetAddress (IP) doesn't match the TargetPortalAddress (Hostname). I thought I'd fixed this but must have made a mistake. Leave it with me and I'll upload a fix today (or possibly tomorrow - updating the unit tests usually takes longer than the fix itself :frowning: )

**Comment by PlagueHO** [comment]
Doh! Just posted my response and saw new one. I'll hold off with making any further changes till I hear back from you.

**Comment by Zuldan** [comment]
I really enjoy this stuff too. If my wife let me I'd spend 18 hours a day writing DSC resources / Pester tests.

I deleted all the iSCSI config, and Set-Target was able to build it all up again. Exciting!

Next thing to test...

We have weird issue where sometimes the Server couldn't connect to the iSCSI target just after a reboot. The the iSCSI status would show 'Reconnecting' to the target and just sit there forever. The manual fix was to Disconnect and then Connect again. If DSC could handle this situation it would remove a ton of Helpdesk calls!

I'm going to see if Set-Target can resolve this situation.

**Comment by PlagueHO** [comment]
Hehe yeah - life - always getting in the way of DSC! Although I think I could do without the Pester tests part :smile:

The resource is actually set up to check the connection and try and connect if it is not connected. However I'm sure it would be easy to add a check for a status of "Reconnecting" - and disconnect it if it isn't connected.

I'll have a poke about in it and see what I can figure out.

**Comment by Zuldan** [comment]
I managed to emulate the 'Reconnecting...' status by doing the following:

1. Power off the VM
2. Disconnect the Network card.
3. Power on the VM
4. Once OS had loaded, enable the Network Card

The idea is that the OS loads without being able to make a connection to the iSCSI target.

In Administrative Tools -> iSCSI Initiator you'll see the iSCSI target is 'Reconnecting...', however in Powershell can only see IsConnect True/False

PS C:\> Get-iSCSISession | select *
AuthenticationType      :
InitiatorInstanceName   :
InitiatorNodeAddress    : iqn.1991-05.com.microsoft:labserver01.pac.bvcorp.corp
InitiatorPortalAddress  :
InitiatorSideIdentifier : 400001370001
IsConnected             : False
IsDataDigest            :
IsDiscovered            : False
IsHeaderDigest          :
IsPersistent            :
NumberOfConnections     : 0
SessionIdentifier       : ffffe001ae4e4020-4000013700000001
TargetNodeAddress       : iqn.2003-10.com.riverbed:labiscsitarget01.000
TargetSideIdentifier    : 0000
PSComputerName          :

Here is the error I get when I run Set-Target

PS C:\> BMD_ciSCSIInitiator\Set-TargetResource @iSCSIParams -Verbose
VERBOSE: Set-TargetResource: Setting iSCSI Initiator 'iqn.2003-10.com.riverbed:labiscsitarget01.000', 'labiscsitarget01' from ''.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target Portal 'labiscsitarget01' from '' exists.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' is connected.
Connect-IscsiTarget : The target name is not found or is marked as hidden from login. 
At C:\Program Files\WindowsPowerShell\Modules\ciSCSI\DSCResources\BMD_ciSCSIInitiator\BMD_ciSCSIInitiator.psm1:479 char:24
+             $Session = Connect-IscsiTarget `
+                        ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_iSCSITarget:ROOT/Microsoft/...SFT_iSCSITarget) [Connect-IscsiTarget], CimException
    + FullyQualifiedErrorId : HRESULT 0xefff0029,Connect-IscsiTarget

**Comment by Zuldan** [comment]
I'm going to close this particular issue because it's resolved. I'll open up the 'Reconnecting' thing as a feature request.
