### ISSUE TITLE
Feature Request: Ability to connect to iSCSI target when GUI status is 'Reconnecting...'

### ISSUE THREAD

**Issue by Zuldan** [PlagueHO/ciSCSI#9]
This feature will help the DSC resource bring the iSCSI connection back online (stay in Desired State) when network issues occur.

To emulate the 'Reconnecting...' status do the following: 

(The idea is that the OS loads without being able to make a connection to the iSCSI target)

1.Power off the VM
2.Disconnect the Network card.
3.Power on the VM
4.Once OS had loaded, enable the Network Card

In Administrative Tools -> iSCSI Initiator you'll see the iSCSI target is 'Reconnecting...', however in Powershell can only see IsConnect True/False

PS C:> Get-iSCSISession | select *
 AuthenticationType :
 InitiatorInstanceName :
 InitiatorNodeAddress : iqn.1991-05.com.microsoft:labserver01.pac.bvcorp.corp
 InitiatorPortalAddress :
 InitiatorSideIdentifier : 400001370001
 IsConnected : False
 IsDataDigest :
 IsDiscovered : False
 IsHeaderDigest :
 IsPersistent :
 NumberOfConnections : 0
 SessionIdentifier : ffffe001ae4e4020-4000013700000001
 TargetNodeAddress : iqn.2003-10.com.riverbed:labiscsitarget01.000
 TargetSideIdentifier : 0000
 PSComputerName :

Here is the error I get when I run Set-Target

PS C:> BMD_ciSCSIInitiator\Set-TargetResource @iSCSIParams -Verbose
 VERBOSE: Set-TargetResource: Setting iSCSI Initiator 'iqn.2003-10.com.riverbed:labiscsitarget01.000', 'labiscsitarget01' from ''.
 VERBOSE: Set-TargetResource: Ensuring iSCSI Target Portal 'labiscsitarget01' from '' exists.
 VERBOSE: Set-TargetResource: Ensuring iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' is connected.
 Connect-IscsiTarget : The target name is not found or is marked as hidden from login. 
 At C:\Program Files\WindowsPowerShell\Modules\ciSCSI\DSCResources\BMD_ciSCSIInitiator\BMD_ciSCSIInitiator.psm1:479 char:24
• $Session = Connect-IscsiTarget `
• ~~~~~~~~~~~~~~~~~~~~~ ◦CategoryInfo : NotSpecified: (MSFT_iSCSITarget:ROOT/Microsoft/...SFT_iSCSITarget) [Connect-IscsiTarget], CimException
◦FullyQualifiedErrorId : HRESULT 0xefff0029,Connect-IscsiTarget

**Comment by PlagueHO** [comment]
Nice work on that info @Zuldan  - that is awesome!

Question: Does your config have the IsPersistent parameter set to $True? If not, does setting it change the behavior?

Also, are you able to post the output of ```Get-iSCSIConnection``` during the "Restarting" phase?

I'll try and replicate the problem here too.

One solution might be to always attempt a reconnect if the "IsConnected" is $false and "IsPersistent" is $True. Because if IsPersistent is $True then no matter what the connection should always be established (unless it the iSCSI target is offline).

**Comment by Zuldan** [comment]
@PlagueHO, I'm trying to enable Persistent (which is thought was renamed to 'Favourites' but it appears to be different in Powershell, weird).

I'm doing the following steps to try enable IsPersistent using the resource but am getting an error.

1. Confirmed Persistent is false
PS C:\> (Get-IscsiSession).IsPersistent
False
2. Offline the disk
3. Disconnect the iSCSI session (GUI shows it as 'Inactive')
4. Run Set-Target

PS C:\> BMD_ciSCSIInitiator\Set-TargetResource @iSCSIParams -Verbose
VERBOSE: Set-TargetResource: Setting iSCSI Initiator 'iqn.2003-10.com.riverbed:labiscsitarget01.000', 'labiscsitarget01' from ''.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target Portal 'labiscsitarget01' from '' exists.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' is connected.
Connect-IscsiTarget : The target has already been logged in via an iSCSI session. 
At C:\Program Files\WindowsPowerShell\Modules\ciSCSI\DSCResources\BMD_ciSCSIInitiator\BMD_ciSCSIInitiator.psm1:479 char:24
+             $Session = Connect-IscsiTarget `
+                        ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_iSCSITarget:ROOT/Microsoft/...SFT_iSCSITarget) [Connect-IscsiTarget], CimException
    + FullyQualifiedErrorId : HRESULT 0xefff003f,Connect-IscsiTarget

I haven't looked at the code but it appears it's trying to Connect to the target and then set the persistence. Looks like it doesn't like have the persistence set when there is a connection.

**Comment by PlagueHO** [comment]
I mean in your DSC configuration there is a parameter in the cISCSIInitiator resource - (e.g. in your @iSCSIParams) are you setting it to $True?

**Comment by Zuldan** [comment]
Sure am!

$iSCSIParams = @{
 Ensure = 'Present'
 TargetPortalAddress = 'labiscsitarget01'
 TargetPortalPortNumber = 3260
 NodeAddress = 'iqn.2003-10.com.riverbed:labiscsitarget01.000'
 IsPersistent = $True
 }

**Comment by PlagueHO** [comment]
Cool! Just wanted to make sure I was doing the same thing as you in my testing.

I've noticed the problem too of not being able to disconnect the iSCSI connection while it is in use (even if it is not connected).

**Comment by Zuldan** [comment]
> I've noticed the problem too of not being able to disconnect the iSCSI connection while it is in use (even if it is not connected).

Yep that's why I offlined the disk and manually disconnected the iSCSI session before running Set-Target. Something strange is going on.

**Comment by PlagueHO** [comment]
Even when using the iSCSI Initiator GUI client it has similar behavior. But I'll see if there is a way to force a reconnect.

**Comment by Zuldan** [comment]
> Even when using the iSCSI Initiator GUI client it has similar behavior. But I'll see if there is a way to force a reconnect.

Yep that is one issue. Would like me to open a seperate issue for that one?

It's weird I can't set IsPersistent with Set-Target when the iSCSI session is disconnected and not in use.

**Comment by PlagueHO** [comment]
So there is no connections reported when you use ```Get-ISCSIConnection```?

I think the issues are all related so we might as well keep them together for now. But if we can be sure they're not related then we can open another issue.

**Comment by Zuldan** [comment]
> So there is no connections reported when you use  Get-ISCSIConnection ?

That is correct

> I think the issues are all related so we might as well keep them together for now. But if we can be sure they're not related then we can open another issue.

No prob

**Comment by PlagueHO** [comment]
I'm running into similar headaches as you are when trying to change the status of a connection once it is connected. The problem seems to be in the iSCSI cmdlets themselves. However, I'll continue working on it and see if I can figure out a way of doing this.

It seems to be that once a VirtualDisk is connected by the iSCSI client then changing it is extremely difficult without taking the disk out of the cluster first (in my case I'm using iSCSI as cluster storage).

**Comment by PlagueHO** [comment]
An example of iSCSI odd behavior:
![2016-05-02_21-37-44](https://cloud.githubusercontent.com/assets/7589164/14951638/89b64c68-10ae-11e6-9d84-181bdceba47b.png)

One other solution to this is that a Resource can request that the OS reboots, and then the LCM will oblige (if it is set to allow reboot). The resource could request a reboot if a session/connection needs to be changed. What is your feeling on that?

**Comment by Zuldan** [comment]
Glad you're seeing issues too. I was starting to think it was something weird in my environment. You've found an interesting issue. Not very consistent.

I'm going to have a play with the cmdlets as well. Will get back to you on the reboot option.

**Comment by PlagueHO** [comment]
You're definitely onto an issue here - I've managed to replicate what you're seeing now:
![2016-05-02_22-15-19](https://cloud.githubusercontent.com/assets/7589164/14952323/94655956-10b3-11e6-86fb-708d0b057098.png)

I had to switch IsPersistent from $True to $False, apply the config, reboot the server then change IsPersistent from $False to $True, apply the config again and then reboot again.

![2016-05-02_22-19-05](https://cloud.githubusercontent.com/assets/7589164/14952417/550d09e2-10b4-11e6-9f8d-5a5047c10348.png)

I think the message "The target name is not found or is marked as hidden from login." indicates this - what I need to know is how/why is it marked as hidden.

**Comment by PlagueHO** [comment]
@Zuldan - I still haven't come up with a decent solution to this yet, but in the meantime I thought I'd release the current dev build into master - which will push it out to PSGallery.

**Comment by Zuldan** [comment]
@PlagueHO, I didn't get a chance to have a look at the cmdlets today. I'm also going to look at the old iscsicli.exe to see if there is a solution with that.

Good idea with releasing the fixes so far. Thank you for changing the versioning convention to 4 segments.

**Comment by Zuldan** [comment]
Actually the versioning is still 3 segment. See ciSCSI/ciSCSI.psd1. Would you consider changing it to 4 segment to align it with your readme.md and MFST DSC standards?

**Comment by PlagueHO** [comment]
Oh - the fourth segment (build number) is automatically assigned by the build/release process. So it gets automatically inserted into the .PSD1 file at that time. So the version in the PSGallery will have the fourth number. But I can adjust it in here as well :)

**Comment by Zuldan** [comment]
Thanks for the explanation. I was just comparing a MFST PSD1 with yours on GitHub. I didn't know PSGallery automatically incremented it.

**Comment by Zuldan** [comment]
I was going to investigate the iSCSI cmdlets today and to see why your resource can't set an exisiting iSCSI connection to IsPersistent = $True even when the disk is offline and the connection Inactive. 

I came across this "For an existing session, if the session is not persistent, it can be made persistent by piping the session to the Register-iSCSISession cmdlet". See https://blogs.msdn.microsoft.com/san/2012/07/31/managing-iscsi-initiator-connections-with-windows-powershell-on-windows-server-2012/

So it looks like it is possible.

**Comment by PlagueHO** [comment]
I've actually fixed the AppVeyor version assignment code now so AppVeyor will still assign the build number but it will also have '1.2.0.0' in the Manifest file :smile: - best of both worlds! The version released to PSGallery will have the full '1.2.0.1234' though (the AppVeyor build number is the last part of the SemVer).

You're right though - this is definitely possible. That is actually what the code is set to do:
https://github.com/PlagueHO/ciSCSI/blob/dev/DSCResources/BMD_ciSCSIInitiator/BMD_ciSCSIInitiator.psm1#L496

However, I'm not piping the session through (rather I'm specifying the session ID). I'll try piping it and see if that resolves it. I'm having trouble replicating the problem again now.

**Comment by PlagueHO** [comment]
@Zuldan - excellent news! Changing the Register/Unregister-IscsiConnection to have the session piped to it seems to have resolved the problem - at least it seems to for me.

Are you able to try the change out? It is still in the separate branch:

https://github.com/PlagueHO/ciSCSI/tree/Enhancement/9-Improve-Reconnect-Handling

If it works OK for you I'll merge the change into dev and release it ASAP.

Thanks!

**Comment by Zuldan** [comment]
@PlagueHO, unfortunately I'm still experiencing the same issue as before. I cannot enable IsPersistent = $True on an existing iSCSI connection, even if I offline the disk and disconnect the iSCSI session.

PS C:\> $iSCSIParams = @{
    Ensure                 = 'Present'
    TargetPortalAddress    = 'labiscsitarget01'
    TargetPortalPortNumber = 3260
    NodeAddress            = 'iqn.2003-10.com.riverbed:labiscsitarget01.000'
    IsPersistent           = $True
}

PS C:\> Import-Module 'C:\Program Files\WindowsPowerShell\Modules\ciSCSI\DSCResources\BMD_ciSCSIInitiator\BMD_ciSCSIInitiator.psm1' -Force
PS C:\> (Get-Content 'C:\Program Files\WindowsPowerShell\Modules\ciSCSI\ciSCSI.psd1')[14]
ModuleVersion = '1.2.0.0'

PS C:\> Get-IscsiSession
AuthenticationType      : NONE
InitiatorInstanceName   : ROOT\ISCSIPRT\0000_0
InitiatorNodeAddress    : iqn.1991-05.com.microsoft:labserver01.pac.bvcorp.corp
InitiatorPortalAddress  : 0.0.0.0
InitiatorSideIdentifier : 400001370000
IsConnected             : True
IsDataDigest            : False
IsDiscovered            : False
IsHeaderDigest          : False
IsPersistent            : False
NumberOfConnections     : 1
SessionIdentifier       : ffffe001ae4e4020-4000013700000012
TargetNodeAddress       : iqn.2003-10.com.riverbed:labiscsitarget01.000
TargetSideIdentifier    : 3f00
PSComputerName          : 

PS C:\> Get-IscsiTarget | Disconnect-IscsiTarget -Confirm:$False
PS C:\> $Session = Get-IscsiSession
PS C:\> $null -eq $Session
True
PS C:\> BMD_ciSCSIInitiator\Set-TargetResource @iSCSIParams -Verbose
VERBOSE: Set-TargetResource: Setting iSCSI Initiator 'iqn.2003-10.com.riverbed:labiscsitarget01.000', 'labiscsitarget01' from ''.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target Portal 'labiscsitarget01' from '' exists.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' is connected.
Connect-IscsiTarget : The target has already been logged in via an iSCSI session. 
At C:\Program Files\WindowsPowerShell\Modules\ciSCSI\DSCResources\BMD_ciSCSIInitiator\BMD_ciSCSIInitiator.psm1:479 char:24
+             $Session = Connect-IscsiTarget `
+                        ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_iSCSITarget:ROOT/Microsoft/...SFT_iSCSITarget) [Connect-IscsiTarget], CimExcepti 
   on
    + FullyQualifiedErrorId : HRESULT 0xefff003f,Connect-IscsiTarget

**Comment by PlagueHO** [comment]
Damn. What happens if you just enter ```Get-iSCSITarget```? Does the target show up?

Are what are you seeing in the iSCSIClient UI - does it show the target as connected? This does look like the same problem I was having where the Target was connected but didn't show in the target list.

**Comment by Zuldan** [comment]
So before I run Set-TargetResource....

```
PS C:\>  Get-iSCSITarget 

IsConnected NodeAddress                                  PSComputerName
----------- -----------                                  --------------
       True iqn.2003-10.com.riverbed:labiscsitarget01.000 
```

GUI says 'Inactive'

I'm going to debug and step through the code and let you know at what point the error occurs. Stand by...

**Comment by Zuldan** [comment]
Actually before I go debug, I did a quick test. I then completely remove the target from the GUI then had the iSCSI target setup by your DSC resource. IsPersistent is now $True. So it appears if the iSCSI Target is initially configured by the GUI, it causes issues for Powershell cmdlets.

Before the removal....

```
PS C:\> Get-IscsiSession
AuthenticationType      : NONE
InitiatorInstanceName   : ROOT\ISCSIPRT\0000_0
InitiatorNodeAddress    : iqn.1991-05.com.microsoft:labserver01.pac.bvcorp.corp
InitiatorPortalAddress  : 0.0.0.0
InitiatorSideIdentifier : 400001370000
IsConnected             : True
IsDataDigest            : False
IsDiscovered            : False
IsHeaderDigest          : False
**IsPersistent            : False**
NumberOfConnections     : 1
SessionIdentifier       : ffffe001ae4e4020-4000013700000012
TargetNodeAddress       : iqn.2003-10.com.riverbed:labiscsitarget01.000
TargetSideIdentifier    : 3f00
PSComputerName          :
```
Ran Set-TargetResource...

```
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\ciSCSI\DSCResources\BMD_ciSCSIInitiator\BMD_ciSCSIInitiator.psm1' -Force
BMD_ciSCSIInitiator\Test-TargetResource @iSCSIParams -Verbose
BMD_ciSCSIInitiator\Set-TargetResource @iSCSIParams -Verbose
VERBOSE: Test-TargetResource: Testing iSCSI Initiator 'iqn.2003-10.com.riverbed:labiscsitarget01.000', labiscsitarget01from ''.
VERBOSE: Test-TargetResource: iSCSI Target Portal labiscsitarget01from '' does not exist but should. Change required.
False
VERBOSE: Set-TargetResource: Setting iSCSI Initiator 'iqn.2003-10.com.riverbed:labiscsitarget01.000', labiscsitarget01from ''.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target Portal labiscsitarget01from '' exists.

InitiatorInstanceName  : 
InitiatorPortalAddress : 
IsDataDigest           : False
IsHeaderDigest         : False
TargetPortalAddress    : labiscsitarget01
TargetPortalPortNumber : 3260
PSComputerName         : 

VERBOSE: Set-TargetResource: iSCSI Target Portal labiscsitarget01from '' has been created.
VERBOSE: Set-TargetResource: Ensuring iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' is connected.
VERBOSE: Set-TargetResource: iSCSI Target 'iqn.2003-10.com.riverbed:labiscsitarget01.000' has been connected.

PS C:\> Get-IscsiSession
AuthenticationType      : NONE
InitiatorInstanceName   : ROOT\ISCSIPRT\0000_0
InitiatorNodeAddress    : iqn.1991-05.com.microsoft:labserver01.pac.bvcorp.corp
InitiatorPortalAddress  : 0.0.0.0
InitiatorSideIdentifier : 400001370000
IsConnected             : True
IsDataDigest            : False
IsDiscovered            : False
IsHeaderDigest          : False
**IsPersistent            : True**
NumberOfConnections     : 1
SessionIdentifier       : ffffe001ae4e4020-4000013700000012
TargetNodeAddress       : iqn.2003-10.com.riverbed:labiscsitarget01.000
TargetSideIdentifier    : 3f00
PSComputerName          :
```

**Comment by PlagueHO** [comment]
Hmmm. That isn't something I had tried.

So to confirm, you had the initiator setup initially via the GUI - without IsPersistent. Then when the DSC resource was applied it tried to use Register-ISCSIConnection to set the IsPersistent on the connection but failed?

I'll go and try this on my test servers and see if I can get the same thing.

**Comment by Zuldan** [comment]
That is correct. In fact, I don't think there is a way in the GUI to set IsPersistent to $True. In the GUI you have 'Favourite Targets' (which the previous target was listed under). 

It says...

> An attempt to restore connections to targets listed here will be made every time this computer restarts"

 So it sounds like Persistent = Favourites...but it's not because you can have the target listed in the Favourites and IsPersisent still $False. Super weird stuff going on.

**Comment by PlagueHO** [comment]
That is correct. IsPersistent is the same as adding the server to Favorites. There is a lot of inconsistencies between the iSCSI cmdlets and the GUI. I still struggle with the different terms used.

**Comment by Zuldan** [comment]
Can you create the iSCSI initiator from scratch (or even better revert a VM snapshot to before iSCSI was ever setup), in the GUI, make sure the target is in favourites and then tell me what your Get-IscsiSession says?

**Comment by PlagueHO** [comment]
I can do one better - I'll make LabBuilder build a new cluster node from scratch with no ISCSI installed. It'll take 15 minutes (and I've got a skype call in a little while) so I'll get back to you as soon as I have a result.

**Comment by Zuldan** [comment]
Ok I'm getting some more inconsistencies. I just checked another two servers. Both of them were setup via GUI, both have targets in favourites and yet one of them has IsPersistent = $False the other has IsPersistent = $True. 

This is driving me nuts! lol

**Comment by Zuldan** [comment]
No rush mate

**Comment by PlagueHO** [comment]
Actually, I stand corrected. I think the IsPersistent is automatically set any time a target is set via the Discovery portal. In fact, I haven't managed to create a connection via the GUI that isn't persistent.

I'm almost tempted to remove the IsPersistent Option entirely and force it to always be a persistent connection. I mean, having connection that _isn't_ persistent when it is configured via DSC is actually pointless. Do you have an opinion on this? I don't actually know if it will actually solve the problem though because the Resource will still need to call Register-ISCSIConnection to make the connection persistent which seems to be where things are going wrong.

Here are the results of my tests:
![1](https://cloud.githubusercontent.com/assets/7589164/15005148/b26dc78c-1214-11e6-84d5-bf3fc889b586.png)
![2](https://cloud.githubusercontent.com/assets/7589164/15005150/b2ae6ce2-1214-11e6-8f4f-9712ed23daf2.png)
![3](https://cloud.githubusercontent.com/assets/7589164/15005145/b214a51c-1214-11e6-9623-0124012af6ed.png)
![4](https://cloud.githubusercontent.com/assets/7589164/15005146/b2426556-1214-11e6-9bdb-a4c00ae7344b.png)
![5](https://cloud.githubusercontent.com/assets/7589164/15005149/b2894a66-1214-11e6-90bd-a48c00500bf0.png)

I have tried the same tests using Hostnames instead of IP Addresses as well, exactly the same results.

**Comment by Zuldan** [comment]
> I mean, having connection that isn't persistent when it is configured via DSC is actually pointless. Do you have an opinion on this?

I totally agree. In a DSC environment having Persistent is pointless. Under the code it should always be True.

On another note, now that Powershell is reporting 'IsPersistent = True', I cannot replicate the 'Reconnecting...' issue I was having. I'm going to close this issue.

Thank you very much for all your assistance with this. Looking forward to the final version being released to master. Can't wait to grab a copy!

**Comment by PlagueHO** [comment]
A pleasure! And thanks for all your help on this too :smile:

I'll merge the changes I made with the Register/Unregister and then release it. I'll leave the IsPersistent in for now, but will raise an issue to remove it. But before I make that change I'll release this version to Master. Will drop a note in here once it's done!

Also, keep in mind that I've requested from MSFT that this resource be added to the community resources so it may change from ciSCSI to xiSCSI in the near future.

**Comment by Zuldan** [comment]
I've gone and grabbed the 1.2.1.0 from the Dev repository to chucked in the lab. I can't compile the MOF file :-(

PSDesiredStateConfiguration\Node : Cannot bind argument to parameter 'ResourceKey' because it is an empty string.

**Comment by PlagueHO** [comment]
I'm just trying the one downloaded from PSGallery now on my Lab. The MOF hadn't change so I'm puzzled by that one! Could there be any older versions or files still lying around?

**Comment by PlagueHO** [comment]
I've pushed Dev to Master which has released this to the PSGallery and aren't seeing the problem you are. I'm wondering if it is just a problem with lots of different files and copies around. :(

**Comment by Zuldan** [comment]
It was my environment. I was trying to assign a variable to your resource properties in the node config file and the variable was empty. Oops. 

Going to push v1.2.1.0 out to production soon.

**Comment by PlagueHO** [comment]
Hehe no worries! :smile: I've been there before sir! Let me know if you run into anything and I'll take a look.

Cheers!
